services:
  - type: web
    name: people-analytics-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: MONGO_URL
        fromDatabase:
          name: people-analytics-db
          property: connectionString
      - key: DB_NAME
        value: people_analytics
      - key: CORS_ORIGINS
        value: https://your-frontend-url.vercel.app
      - key: EMERGENT_LLM_KEY
        sync: false